
services:
  # drone_sim
  drone_sim:
    build:
      context: ../.. # root: DroneSimEnv
      dockerfile: Docker/Dockerfile/Dockerfile.drone_sim
    container_name: drone_sim
    privileged: true
    network_mode: "host"
    ipc: host
    shm_size: '2gb'    
    stdin_open: true   # -i options
    tty: true         # -t options
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # drone_sim_ws
      - ../../Drone_sim/drone_sim_ws/src:/DroneSimEnv/drone_sim_ws/src:rw
    deploy:            # GPU
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # ground
  ground:
    build:
      context: ../.. # root: DroneSimEnv
      dockerfile: Docker/Dockerfile/Dockerfile.ground
    container_name: ground
    privileged: true   
    network_mode: "host"
    ipc: host
    stdin_open: true   # -i options
    tty: true         # -t options
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # ground_ws
      - ../../Ground/ground_ws/src:/DroneSimEnv/ground_ws/src:rw
    deploy:           # GPU
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # copmanion
  companion:
    build:
      context: ../.. # root: DroneSimEnv
      dockerfile: Docker/Dockerfile/Dockerfile.companion
    container_name: companion
    privileged: true
    network_mode: "host"
    ipc: host
    shm_size: '2gb'    
    stdin_open: true   # -i options
    tty: true          # -t options
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      #companion_ws
      - ../../Companion/companion_ws/src:/DroneSimEnv/companion_ws/src:rw
    deploy:          # GPU
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
