
services:
  # drone_sim
  drone_sim:
    build:
      context: ../.. # root: DroneSimEnv
      dockerfile: Docker/Dockerfile/Dockerfile.drone_sim
    container_name: drone_sim
    privileged: true
    network_mode: "host"
    ipc: host
    shm_size: '2gb'    
    stdin_open: true   # -i options
    tty: true          # -t options
    environment:
      # GUI, WSLg settings
      - DISPLAY=${DISPLAY:-:0}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/mnt/wslg/runtime-dir}
      - PULSE_SERVER=${PULSE_SERVER:-unix:/mnt/wslg/PulseServer}
      - QT_X11_NO_MITSHM=1
      # NVIDIA / GPU settings
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA
      - LIBGL_ALWAYS_SOFTWARE=0
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      # socket , WSLg volumes for GUI forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl
      # drone_sim_ws
      - ../../Drone_sim/drone_sim_ws/src:/DroneSimEnv/drone_sim_ws/src:rw
    devices:
      # WSL2 GPU virtual device
      - /dev/dxg:/dev/dxg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # ground
  ground:
    build:
      context: ../.. # root: DroneSimEnv
      dockerfile: Docker/Dockerfile/Dockerfile.ground
    container_name: ground
    privileged: true   
    network_mode: "host"
    ipc: host
    stdin_open: true
    tty: true
    environment:
      # GUI, WSLg settings
      - DISPLAY=${DISPLAY:-:0}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/mnt/wslg/runtime-dir}
      - PULSE_SERVER=${PULSE_SERVER:-unix:/mnt/wslg/PulseServer}
      - QT_X11_NO_MITSHM=1
      # NVIDIA / GPU settings
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA
      - LIBGL_ALWAYS_SOFTWARE=0
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl
      # ground_ws
      - ../../Ground/ground_ws/src:/DroneSimEnv/ground_ws/src:rw
    devices:
      - /dev/dxg:/dev/dxg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  # companion
  companion:
    build:
      context: ../.. # root: DroneSimEnv
      dockerfile: Docker/Dockerfile/Dockerfile.companion
    container_name: companion
    privileged: true
    network_mode: "host"
    ipc: host
    shm_size: '2gb'    
    stdin_open: true
    tty: true
    environment:
      # GUI, WSLg settings
      - DISPLAY=${DISPLAY:-:0}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/mnt/wslg/runtime-dir}
      - PULSE_SERVER=${PULSE_SERVER:-unix:/mnt/wslg/PulseServer}
      - QT_X11_NO_MITSHM=1
      # NVIDIA / GPU settings
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - LD_LIBRARY_PATH=/usr/lib/wsl/lib
      - MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA
      - LIBGL_ALWAYS_SOFTWARE=0
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /usr/lib/wsl:/usr/lib/wsl
      #companion_ws
      - ../../Companion/companion_ws/src:/DroneSimEnv/companion_ws/src:rw
    devices:
      - /dev/dxg:/dev/dxg
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
